language: java
sudo: required
addons: 
 sonarcloud:
    organization: "oxygenxml-github"
    token: "${SONAR_CLOUD_TOKEN}"

dist: trusty
jdk:
 - oraclejdk8
matrix:
  fast_finish: true
install: true
before_script:
  - chmod +x travis/deploy.sh
  - chmod +x travis/checkForTag.sh
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${MY_GH_TOKEN_OXYGEN}:@github.com" > .git/credentials
  - ./travis/checkForTag.sh
script:
  - mvn clean
  - mvn install 
  - wget https://raw.githubusercontent.com/oxygenxml/oxygen-resources-converter/master/travis/install-openjdk11.sh && . ./install-openjdk11.sh
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
before_deploy:
  - ./travis/deploy.sh
deploy:
  provider: releases
  api_key: ${MY_GH_TOKEN_OXYGEN}
  file:
    - target/oxygen-batch-converter-${TRAVIS_TAG}-plugin.jar
    - target/addon.xml
  skip_cleanup: true
  on:
    tags: true
